/*
 * This file was automatically generated by EvoSuite
 * Sat Apr 11 21:47:05 GMT 2020
 */

package org.gjt.sp.jedit.textarea;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.gjt.sp.jedit.View;
import org.gjt.sp.jedit.textarea.JEditTextArea;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class JEditTextArea_ESTest extends JEditTextArea_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      JEditTextArea.doWordCount((View) null, "");
  }

//  @Test(timeout = 4000)
//  public void test1()  throws Throwable  {
//      View view0 = mock(View.class, new ViolatedAssumptionAnswer());
//      // Undeclared exception!
//      try { 
//        JEditTextArea.doWordCount(view0, (String) null);
//        fail("Expecting exception: NullPointerException");
//      
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//         verifyException("org.gjt.sp.jedit.textarea.JEditTextArea", e);
//      }
//  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      // Undeclared exception!
      try { 
        JEditTextArea.getFoldPainterName();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.gjt.sp.jedit.jEdit", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      JEditTextArea.doWordCount((View) null, "% %:");
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      JEditTextArea jEditTextArea0 = null;
      try {
        jEditTextArea0 = new JEditTextArea((View) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.gjt.sp.jedit.jEdit", e);
      }
  }
}
