/*
 * This file was automatically generated by EvoSuite
 * Sat Apr 11 17:22:53 GMT 2020
 */

package org.gjt.sp.jedit.textarea;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.Component;
import javax.swing.JPopupMenu;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.gjt.sp.jedit.textarea.TextArea;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TextArea_ESTest extends TextArea_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      int int0 = 0;
      // Undeclared exception!
      try { 
        TextArea.showPopupMenu((JPopupMenu) null, (Component) null, 0, 0, true);
        fail("Expecting exception: NullPointerException");

      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.gjt.sp.util.GenericGUIUtilities", e);
      }
  }
}