/*
 * This file was automatically generated by EvoSuite
 * Sat Apr 11 17:13:18 GMT 2020
 */

package org.gjt.sp.jedit;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.gjt.sp.jedit.SetViewTitle;
import org.gjt.sp.jedit.View;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SetViewTitle_ESTest extends SetViewTitle_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SetViewTitle setViewTitle0 = new SetViewTitle();
      setViewTitle0.setUserTitle2("");
      String string0 = setViewTitle0.getUserTitle();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SetViewTitle setViewTitle0 = new SetViewTitle();
      // Undeclared exception!
      try { 
        setViewTitle0.showUserTitleDialog((View) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.gjt.sp.jedit.jEdit", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SetViewTitle setViewTitle0 = new SetViewTitle();
      setViewTitle0.setUserTitle2("O");
      String string0 = setViewTitle0.getUserTitle();
      assertEquals("O", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      SetViewTitle setViewTitle0 = new SetViewTitle();
      String string0 = setViewTitle0.getUserTitle();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      SetViewTitle setViewTitle0 = new SetViewTitle();
      // Undeclared exception!
      try { 
        setViewTitle0.setUserTitle("Wc+:", (View) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.gjt.sp.jedit.SetViewTitle", e);
      }
  }
}
