/*
 * This file was automatically generated by EvoSuite
 * Sat Apr 11 02:45:26 GMT 2020
 */

package org.gjt.sp.jedit;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.HeadlessException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.gjt.sp.jedit.Buffer;
import org.gjt.sp.jedit.View;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class View_ESTest extends View_ES_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try { 
        View.getDockingFrameworkName();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.gjt.sp.jedit.jEdit", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      View.ViewConfig view_ViewConfig0 = null;
      try {
        view_ViewConfig0 = new View.ViewConfig(true);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.gjt.sp.jedit.jEdit", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      View.ViewConfig view_ViewConfig0 = null;
      try {
        view_ViewConfig0 = new View.ViewConfig(false);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.gjt.sp.jedit.jEdit", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      View.ViewConfig view_ViewConfig0 = new View.ViewConfig();
      View view0 = null;
      try {
        view0 = new View((Buffer) null, view_ViewConfig0);
        fail("Expecting exception: HeadlessException");
      
      } catch(HeadlessException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.awt.GraphicsEnvironment", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      View.ViewConfig view_ViewConfig0 = new View.ViewConfig(true, "", 2554, 0, (-1907), 2554, (-2366));
      assertEquals((-2366), view_ViewConfig0.extState);
      assertEquals(0, view_ViewConfig0.y);
      assertTrue(view_ViewConfig0.plainView);
      assertEquals((-1907), view_ViewConfig0.width);
      assertEquals(2554, view_ViewConfig0.height);
      assertEquals(2554, view_ViewConfig0.x);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      // Undeclared exception!
      try { 
        View.getDockingFrameworkProvider();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.gjt.sp.jedit.jEdit", e);
      }
  }
}
